### ISSUE TITLE
Mouse does not alter image

### ISSUE THREAD

**Issue by fuzzyfazzy** [pascscha/FaceChanger#1]
Really weird issue i am having.

Neither the left or right mouse button does anything when pressed - what am i doing wrong?

**Comment by mingyu6yang** [comment]
I have a same problem, could you sovle that?

**Comment by fuzzyfazzy** [comment]
Unfortunately no.

**Comment by pascscha** [comment]
Can you give me some more information? What OS are you using, what python version, what openCV version. Are there any error messages?

Do you get any output with this test script?
```Python
import cv2
import numpy as np


def mouseevent(*args, **kwargs):
    print(args, kwargs)


windowname = "FaceChanger"
cv2.namedWindow(windowname, cv2.WINDOW_GUI_NORMAL)
cv2.setMouseCallback(windowname, mouseevent)

black = np.zeros((100, 100, 3), dtype=np.uint8)
cv2.imshow(windowname, black)
cv2.waitKey(0)
```

**Comment by mingyu6yang** [comment]
this is output:
(4, 29, 78, 0, None) {}
(0, 29, 78, 0, None) {}
(7, 29, 78, 1, None) {}
(4, 29, 78, 0, None) {}



Any mouse click events fail to respond.
windows11 , python3.9 opencv-python4.7.0.72


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pascscha/FaceChanger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 下午5:54
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [pascscha/FaceChanger] Mouse does not alter image (Issue #1)





 
Can you give me some more information? What OS are you using, what python version, what openCV version. Are there any error messages?
 
Do you get any output with this test script?
 import cv2 import numpy as np def clicked(*args, **kwargs):     print(args, kwargs) windowname = "FaceChanger" cv2.namedWindow(windowname, cv2.WINDOW_GUI_NORMAL) cv2.setMouseCallback(windowname, clicked) black = np.zeros((100, 100, 3), dtype=np.uint8) cv2.imshow(windowname, black) cv2.waitKey(0)

**Comment by pascscha** [comment]
Ok, and what does this print:

```Python
import cv2
print(cv2.EVENT_FLAG_LBUTTON, cv2.EVENT_FLAG_RBUTTON)
```

**Comment by pascscha** [comment]
Also, does face detection itself work? `./main.py -f filters/long-nose.json`

If you run one of the preset filters does it change the image?

**Comment by mingyu6yang** [comment]
no，nothing happend...




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "pascscha/FaceChanger"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Jun 15, 2023 06:25 PM
***@***.***&gt;;
Cc:&nbsp;" ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [pascscha/FaceChanger] Mouse does not alter image (Issue #1)





 
Also, does face detection itself work? ./main.py -f filters/long-nose.json
 
If you run one of the preset filters does it change the image?

**Comment by pascscha** [comment]
The the issue is probably not with the mouse clicks not registering, but the face not being detected

**Comment by pascscha** [comment]
Does it work when running against the stock video?

`./main.py -i media/stock.mp4 -f filters/long-nose.json`

**Comment by mingyu6yang** [comment]
ops,face has been detected, but not transform




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "pascscha/FaceChanger"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Jun 15, 2023 06:32 PM
***@***.***&gt;;
Cc:&nbsp;" ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [pascscha/FaceChanger] Mouse does not alter image (Issue #1)





 
The the issue is probably not with the mouse clicks not registering, but the face not being detected

**Comment by mingyu6yang** [comment]
no, transform does not work




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pascscha/FaceChan发送ger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 晚上6:33
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [pascscha/FaceChanger] Mouse does not alter image (Issue #1)





 
Does it work when running against the stock video?
 
./main.py -i media/stock.mp4 -f filters/long-nose.json

**Comment by pascscha** [comment]
How do you know the face has been detected?

Can you pull my latest commit and see if there's any new error messages?

**Comment by mingyu6yang** [comment]
face is detected.
but 85 points is not adjusted ,new feature is same as old feature




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "pascscha/FaceChanger"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Jun 15, 2023 06:40 PM
***@***.***&gt;;
Cc:&nbsp;" ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [pascscha/FaceChanger] Mouse does not alter image (Issue #1)





 
How do you know the face has been detected?
 
Can you pull my latest commit and see if there's any new error messages?

**Comment by pascscha** [comment]
Can you pull my latest commit and see if there's any new error messages?

**Comment by mingyu6yang** [comment]
> Can you pull my latest commit and see if there's any new error messages?

no error, 
but i found     
subdiv.insert([p])  is not work? that is reason!

**Comment by mingyu6yang** [comment]
oh, i solve it.
transform#11, use this
    for x,y in points:
        try:
            subdiv.insert((int(x), int(y)))
now, it works!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
